### ISSUE TITLE
No pitch-bending

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [sykhro/vgmtrans-qt#7]
So I loaded music from any compatible SNES game and we didn't have pitch-bending at all.

**To Reproduce**
Steps to reproduce the problem.
1. Check if there's any pitch bending.
2. Load the song
3. Play the song

**Expected behavior**
I expected pitch-bending to happen, as the original vgmtrans didn't even have it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans continuous-refactor
 - SHA-256: b65518bf1ea9d83d16b37836580416d6c09b2f757812c1026451538559adbf48

**Additional context**
This song features pitch-bendings even at the start. That song was "Battle Against a Machine" from _EarthBound_. I remember hearing it on the original vgmtrans and it lacked the pitch bend, too.

**Comment by sykhro** [comment]
sorry, this is just (an outdated) qt frontend for vgmtrans, no new features. this has been a problem for ages, we have never been able to find a satisfying solution.. it might be time to put a couple hacks together so that at least some formats can have working pitch bends
